package com.agusstkd.goodlife.presentation.screen.add.routine.steps

import com.agusstkd.goodlife.core.datetime.language.CreateItemSharedTexts
import com.agusstkd.goodlife.core.datetime.language.CreateRoutineTexts

internal fun previewRoutineTexts() = CreateRoutineTexts(
    screenTitle = "Nueva rutina",
    typeBadge = "RUTINA",
    stepOf = "Paso %d de %d",
    nextButton = "Siguiente",
    backButton = "Atrás",
    createButton = "Crear rutina",
    successTitle = "Rutina creada con éxito",
    difficultySectionTitle = "Dificultad",
    difficultyBeginner = "Principiante",
    difficultyIntermediate = "Intermedio",
    difficultyAdvanced = "Avanzado",
    goalSectionTitle = "Objetivo principal",
    goalPlaceholder = "Seleccionar objetivo",
    goalMuscleGain = "Ganar músculo",
    goalWeightLoss = "Perder peso",
    goalStrength = "Fuerza",
    goalEndurance = "Resistencia",
    goalFlexibility = "Flexibilidad",
    workoutsTitle = "Entrenamientos",
    workoutsSubtitle = "Definí la rotación de workouts",
    addWorkout = "Añadir entrenamiento",
    workoutNamePlaceholder = "Ej: Push Day",
    deleteWorkoutConfirm = "¿Eliminar este entrenamiento?",
    yourExercises = "Tus ejercicios",
    catalogTitle = "Catálogo de ejercicios",
    searchPlaceholder = "Buscar ejercicios...",
    filterAll = "Todos",
    addExerciseButton = "Agregar",
    editSetsButton = "Editar",
    saveWorkoutButton = "Guardar workout",
    setsLabel = "Sets",
    repsLabel = "Reps",
    weightLabel = "Peso (kg)",
    addSetButton = "Agregar set",
    notesPlaceholder = "Notas del ejercicio (opcional)",
    summaryTitle = "Resumen de rutina",
    activateToggle = "Activar esta rutina ahora",
    exercisesCount = "%d ejercicios",
    setsCount = "%d sets totales",
    errorNameEmpty = "",
    errorNoDifficulty = "",
    errorNoGoal = "",
    errorNoDays = "",
    errorNoWorkouts = "",
    errorWorkoutNoExercises = "",
    errorEndBeforeStart = "",
    errorServer = "",
    errorNetwork = "",
)

internal fun previewSharedTexts() = CreateItemSharedTexts(
    fieldTitleLabel = "Nombre",
    fieldTitlePlaceholder = "Ej: Rutina de fuerza",
    fieldDescriptionLabel = "Descripción",
    fieldDescriptionPlaceholder = "Opcional",
    whenSectionTitle = "¿Cuándo?",
    modeOnce = "Una vez",
    modeRepeats = "Se repite",
    daysRowTitle = "Días de entrenamiento",
    fromDateLabel = "Desde",
    toDateLabel = "Hasta",
    noEndDate = "Sin fecha de fin",
    hasEndDate = "Fecha de fin",
    noSpecificTime = "Sin hora específica",
    timeLabel = "Hora",
    reminderLabel = "Recordatorio",
    cancelButton = "Cancelar",
    confirmLabel = "Confirmar",
    cancelLabel = "Cancelar",
    retryLabel = "Reintentar",
)
