package com.agusstkd.goodlife.presentation.screen.add.mealplan.steps

import com.agusstkd.goodlife.core.datetime.language.CreateItemSharedTexts
import com.agusstkd.goodlife.core.datetime.language.CreateMealPlanTexts
import com.agusstkd.goodlife.domain.model.nutrition.Ingredient
import com.agusstkd.goodlife.domain.model.nutrition.MealSummary
import com.agusstkd.goodlife.domain.model.nutrition.MealType
import com.agusstkd.goodlife.presentation.screen.add.mealplan.model.CreateMealPlanUiState
import kotlinx.collections.immutable.toImmutableList

internal fun previewMealPlanTexts() = CreateMealPlanTexts(
    screenTitle = "Nuevo plan de comida",
    typeBadge = "COMIDA",
    stepOf = "Paso %d de %d",
    nextButton = "Siguiente",
    backButton = "Atrás",
    createPlanButton = "Crear plan",
    successTitle = "Plan creado con éxito",
    loadingTitle = "Creando tu plan...",
    searchMealPlaceholder = "Buscar comida...",
    filterAll = "Todos",
    chooseMealButton = "Elegir",
    createNewMealButton = "Crear nueva comida",
    newMealNameLabel = "Nombre",
    newMealNamePlaceholder = "Ej: Ensalada de pollo",
    newMealDescriptionLabel = "Descripción",
    newMealDescriptionPlaceholder = "Opcional",
    newMealTypeLabel = "Tipo de comida",
    macrosSummaryTitle = "Macros totales",
    macroProteinLabel = "Proteína",
    macroCarbsLabel = "Carbos",
    macroFatLabel = "Grasas",
    myIngredientsSectionTitle = "Mis ingredientes",
    ingredientCatalogSectionTitle = "Catálogo de ingredientes",
    searchIngredientPlaceholder = "Buscar ingrediente...",
    addIngredientButton = "Agregar",
    createCustomIngredientButton = "+ Crear ingrediente custom",
    quantitySheetQuantityLabel = "Cantidad",
    quantitySheetUnitLabel = "Unidad",
    quantitySheetConfirmButton = "Confirmar",
    quantitySheetCancelButton = "Cancelar",
    createIngredientDialogTitle = "Nuevo ingrediente",
    ingredientNameLabel = "Nombre",
    ingredientNamePlaceholder = "Ej: Pechuga de pollo",
    ingredientBrandLabel = "Marca",
    ingredientBrandPlaceholder = "Opcional",
    ingredientServingSizeLabel = "Porción",
    ingredientCaloriesLabel = "Calorías",
    ingredientProteinLabel = "Proteínas (g)",
    ingredientCarbsLabel = "Carbohidratos (g)",
    ingredientFatLabel = "Grasas (g)",
    saveIngredientButton = "Guardar ingrediente",
    mealSummaryTitle = "Resumen de la comida",
    mealTypeSectionTitle = "Tipo de comida",
    errorNoMealSelected = "",
    errorMealNameEmpty = "",
    errorNoIngredients = "",
    errorNoMealType = "",
    errorNoDays = "",
    errorEndBeforeStart = "",
    errorQuantityZero = "",
    errorIngredientNameEmpty = "",
    errorServer = "",
    errorNetwork = "",
    quantitySheetMacroTooltip = "",
)

internal fun previewSharedTexts() = CreateItemSharedTexts(
    fieldTitleLabel = "Nombre",
    fieldTitlePlaceholder = "Ej: Almuerzo saludable",
    fieldDescriptionLabel = "Descripción",
    fieldDescriptionPlaceholder = "Opcional",
    whenSectionTitle = "¿Cuándo?",
    modeOnce = "Una vez",
    modeRepeats = "Se repite",
    daysRowTitle = "Días de la semana",
    fromDateLabel = "Desde",
    toDateLabel = "Hasta",
    noEndDate = "Sin fecha de fin",
    hasEndDate = "Fecha de fin",
    noSpecificTime = "Sin hora específica",
    timeLabel = "Hora",
    reminderLabel = "Recordatorio",
    cancelButton = "Cancelar",
    confirmLabel = "Confirmar",
    cancelLabel = "Cancelar",
    retryLabel = "Reintentar",
    loadingMessage = "Esto solo tomará un momento...",
    errorTitle = "No se pudo guardar",
)

internal fun previewMealTypeEntries() = listOf(
    MealType.BREAKFAST to "Desayuno",
    MealType.LUNCH to "Almuerzo",
    MealType.DINNER to "Cena",
    MealType.SNACK to "Merienda",
)

internal fun previewMealCatalog() = listOf(
    MealSummary(
        id = 1,
        name = "Ensalada César",
        description = "Clásica ensalada con aderezo césar y crutones",
        imageUrl = null,
        prepTimeMinutes = 15,
        servingSize = 1.0,
        servingUnit = "porción",
        calories = 320.0,
        protein = 18.0,
        carbs = 22.0,
        fat = 14.0,
        isGlobal = true,
    ),
    MealSummary(
        id = 2,
        name = "Pollo a la plancha con arroz",
        description = null,
        imageUrl = null,
        prepTimeMinutes = 30,
        servingSize = 1.0,
        servingUnit = "porción",
        calories = 480.0,
        protein = 42.0,
        carbs = 38.0,
        fat = 8.0,
        isGlobal = false,
    ),
).toImmutableList()

internal fun previewIngredientCatalog() = listOf(
    Ingredient(
        id = 1,
        name = "Pechuga de pollo",
        brand = "Acme Foods",
        servingSize = 100.0,
        servingUnit = "g",
        calories = 165.0,
        protein = 31.0,
        carbs = 0.0,
        fat = 3.6,
        isGlobal = true,
        imageUrl = null,
    ),
    Ingredient(
        id = 2,
        name = "Arroz integral",
        brand = null,
        servingSize = 100.0,
        servingUnit = "g",
        calories = 123.0,
        protein = 2.6,
        carbs = 23.0,
        fat = 0.9,
        isGlobal = true,
        imageUrl = null,
    ),
    Ingredient(
        id = 3,
        name = "Brócoli",
        brand = null,
        servingSize = 100.0,
        servingUnit = "g",
        calories = 34.0,
        protein = 2.8,
        carbs = 7.0,
        fat = 0.4,
        isGlobal = true,
        imageUrl = null,
    ),
).toImmutableList()

internal fun previewMealPlanUiState() = CreateMealPlanUiState(
    mealCatalog = previewMealCatalog(),
)
